package edu.tdse.models.dto.response;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "Response model containing complete post information")
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class PostResponseDTO {

    @Schema(
        description = "Unique identifier of the post generated by the system",
        example = "507f1f77bcf86cd799439011"
    )
    private String postId;

    @Schema(
        description = "The text content of the post",
        example = "Hello Twitter! This is my first post.",
        maxLength = 280
    )
    private String message;

    @Schema(
        description = "Unique identifier of the user who created the post",
        example = "507f1f77bcf86cd799439012"
    )
    private String userId;

    @Schema(
        description = "Unique identifier of the stream where the post is published",
        example = "507f1f77bcf86cd799439013"
    )
    private String streamId;
}