spring.application.name=Twitter
server.port=4040

#AUTH0
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-0f5r52ow7l1hoqa6.auth0.com/

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.show-actuator=false
springdoc.api-docs.groups.enabled=true